name: Tests

on:
  - pull_request
  - push

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        allow-failure: [false]
        include:
          - php: '8.0'
            allow-failure: true
          - php: '8.1'
            allow-failure: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apcu

      - name: "Run Tests${{ matrix.allow-failure && ' (allowing failures, php version not supported yet)' }}"
        run: |
          php ./tests/run.php
        continue-on-error: "${{ matrix.allow-failure == true }}"
